test and fix bug
dat26061994/demoApp pull request #4
Opened 2017-04-26 10:35 UTC by dat26061994

to day, i test demo and fix teamplate

2017-04-26 10:51 UTC, 4c0n requested changes

2017-04-26 10:51 UTC, 4c0n commented on resources/views/user/master.blade.php
>                  <p class="pull-left">Copyright © 2013 E-Shopper. All rights reserved.</p>
Is this a downloaded template?

2017-04-26 10:51 UTC, 4c0n commented on public/user/css/main.css
> +@media (max-width: 480px) {
I think bootstrap provides a way to do this. http://getbootstrap.com/css/#responsive-utilities-classes
Angular can also help you with this: https://material.angularjs.org/latest/layout/introduction

But you can use media queries is you want.

2017-04-26 10:51 UTC, 4c0n commented on app/Http/Controllers/UserController.php
> +        } else {
This else statement is empty.

2017-04-26 10:51 UTC, 4c0n commented on app/Http/Controllers/UserController.php
> +        $isset = count($user);
A better name for this variable would be $count

2017-04-27 02:18 UTC, dat26061994 commented
Thank you, i will fix it now

2017-04-26 17:51 GMT+07:00 Youri Westerman <notifications@github.com>:

> *@4c0n* requested changes on this pull request.
> ------------------------------
>
> In resources/views/user/master.blade.php
> <https://github.com/dat26061994/demoApp/pull/4#discussion_r113420243>:
>
> >
> -            </div>
> -        </div>
> -    </div>
>
>      <div class="footer-bottom">
>          <div class="container">
>              <div class="row">
>                  <p class="pull-left">Copyright © 2013 E-Shopper. All rights reserved.</p>
>
> Is this a downloaded template?
> ------------------------------
>
> In public/user/css/main.css
> <https://github.com/dat26061994/demoApp/pull/4#discussion_r113421175>:
>
> > @@ -12,6 +12,11 @@ body {
>    position: relative;
>    font-weight:400px;
>  }
> +@media (max-width: 480px) {
>
> I think bootstrap provides a way to do this. http://getbootstrap.com/css/#
> responsive-utilities-classes
> Angular can also help you with this: https://material.angularjs.
> org/latest/layout/introduction
>
> But you can use media queries is you want.
> ------------------------------
>
> In app/Http/Controllers/UserController.php
> <https://github.com/dat26061994/demoApp/pull/4#discussion_r113421246>:
>
> > @@ -60,24 +61,36 @@ public function getEdit($id)
>      {
>          $userModel = new User();
>          $user = $userModel->findUser($id);
> -        return view('admin.user.edit', compact('user', 'id'));
> +        $isset = count($user);
> +        if ($isset > 0) {
> +            return view('admin.user.edit', compact('user', 'id'));
> +        } else {
>
> This else statement is empty.
> ------------------------------
>
> In app/Http/Controllers/UserController.php
> <https://github.com/dat26061994/demoApp/pull/4#discussion_r113421290>:
>
> > @@ -60,24 +61,36 @@ public function getEdit($id)
>      {
>          $userModel = new User();
>          $user = $userModel->findUser($id);
> -        return view('admin.user.edit', compact('user', 'id'));
> +        $isset = count($user);
>
> A better name for this variable would be $count
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dat26061994/demoApp/pull/4#pullrequestreview-34805504>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AaYGVwjGLju6ZFT63gMkj_5-YpbrPZ0Lks5rzyG1gaJpZM4NIrLJ>
> .
>

2017-04-27 02:24 UTC, merged