Fixvalidate
dat26061994/demoApp pull request #5
Opened 2017-04-27 10:27 UTC by dat26061994

To day, i fix validate input Form

2017-04-27 10:48 UTC, kakeyang commented on app/Http/Controllers/ProductController.php
>          $this->validate($request,
Validation rule should be written in Controller?

2017-04-27 10:49 UTC, kakeyang commented
I see you committed some test image files but you don't need to do that.

2017-04-28 02:29 UTC, 4c0n requested changes

2017-04-28 02:29 UTC, 4c0n commented on app/Http/Controllers/AdminUserController.php
> +                'txtName' => 'required|regex:/(^[A-Za-z ]+$)+/',
Is txtName the name of a person? Be careful with this regex people can also have a "-" character in their name.

2017-04-28 02:29 UTC, 4c0n commented on app/Http/Controllers/ProductController.php
> +        $file_name = $product->rand_string(10) . '-' . $request->file('fImages')->getClientOriginalName();
Please use camelCase for variable names. I think phpcs will tell you the same.

2017-04-28 02:29 UTC, 4c0n commented on app/Http/Controllers/ProductController.php
> +                'txtDescription' => 'max:300|regex:/(^[A-Za-z ]+$)+/',
You can only have letters in the description? What about numbers, ".,-?!/", etc..?

2017-04-28 02:29 UTC, 4c0n commented on app/product.php
> +    function rand_string($length)
This function should probably be in a Helper class:
https://laravel.com/docs/5.4/helpers

2017-04-28 07:29 UTC, merged